apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo-simple
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: kargo-simple-*
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/makigg/kargo-simple.git
